export type Track = {
  id: number;
  title: string;
  artist: string;
  genre: string;
  plays: number;
  color: string;
  filename: string; // WAVファイル名
};

export const tracks: Track[] = [
  {
    id: 1,
    title: "Welcome to Aipaku",
    artist: "AI-SONG",
    genre: "Pop",
    plays: 6430,
    color: "#D65076",
    filename: "Welcome to Aipaku.wav",
  },
  {
    id: 2,
    title: "Ice Cream Wonderland",
    artist: "AI-SONG",
    genre: "Pop",
    plays: 5120,
    color: "#5DB89A",
    filename: "Ice Cream Wonderland.wav",
  },
  {
    id: 3,
    title: "アイ・アイ・I LOVE ICE CREAM",
    artist: "AI-SONG",
    genre: "Pop",
    plays: 4780,
    color: "#E8A0BF",
    filename: "アイ・アイ・I LOVE ICE CREAM.wav",
  },
  {
    id: 4,
    title: "おいしい呪文",
    artist: "AI-SONG",
    genre: "J-Pop",
    plays: 4210,
    color: "#FFB347",
    filename: "おいしい呪文.wav",
  },
  {
    id: 5,
    title: "Ice Cream Syndrome",
    artist: "AI-SONG",
    genre: "Rock",
    plays: 3842,
    color: "#6A8FC9",
    filename: "Ice Cream Syndrome.wav",
  },
  {
    id: 6,
    title: "icecream holic",
    artist: "AI-SONG",
    genre: "Pop",
    plays: 3760,
    color: "#FF8C94",
    filename: "icecream holic.wav",
  },
  {
    id: 7,
    title: "Meltingin our hearts",
    artist: "AI-SONG",
    genre: "Ballad",
    plays: 3300,
    color: "#B8A9C9",
    filename: "Melting in our hearts.wav",
  },
  {
    id: 8,
    title: "8月の花火と君とアイス",
    artist: "AI-SONG",
    genre: "J-Pop",
    plays: 3100,
    color: "#F5A623",
    filename: "8月の花火と君とアイス (Remastered_v4.5).wav",
  },
  {
    id: 9,
    title: "チョコミン党",
    artist: "AI-SONG",
    genre: "Party",
    plays: 2971,
    color: "#5DB89A",
    filename: "チョコミン党(V5).wav",
  },
  {
    id: 10,
    title: "Heat Shock ～溶けない約束～",
    artist: "AI-SONG",
    genre: "Pop",
    plays: 2840,
    color: "#E55B4D",
    filename: "Heat Shock ～溶けない約束～(v5).wav",
  },
  {
    id: 11,
    title: "Scoop Me Up",
    artist: "AI-SONG",
    genre: "Dance",
    plays: 2750,
    color: "#FFD700",
    filename: "Scoop Me Up.wav",
  },
  {
    id: 12,
    title: "Ice Cream Virtual City",
    artist: "AI-SONG",
    genre: "EDM",
    plays: 2640,
    color: "#7B68EE",
    filename: "Ice Cream Virtual City（v5）.wav",
  },
  {
    id: 13,
    title: "flavor forever",
    artist: "AI-SONG",
    genre: "R&B",
    plays: 2540,
    color: "#D2691E",
    filename: "flavor forever.wav",
  },
  {
    id: 14,
    title: "La La La Love ice cream",
    artist: "AI-SONG",
    genre: "Pop",
    plays: 2480,
    color: "#FF69B4",
    filename: "La La La Love ice cream.wav",
  },
  {
    id: 15,
    title: "アイスクリームと黄昏の街",
    artist: "AI-SONG",
    genre: "City Pop",
    plays: 2350,
    color: "#F4A460",
    filename: "アイスクリームと黄昏の街（v5）.wav",
  },
  {
    id: 16,
    title: "I am ice cream",
    artist: "AI-SONG",
    genre: "Pop",
    plays: 2200,
    color: "#87CEEB",
    filename: "I am ice cream（she-v5）.wav",
  },
  {
    id: 17,
    title: "Foolish man",
    artist: "AI-SONG",
    genre: "Rock",
    plays: 2100,
    color: "#708090",
    filename: "Foolish man.wav",
  },
  {
    id: 18,
    title: "Ice cream paradise",
    artist: "AI-SONG",
    genre: "Pop",
    plays: 2050,
    color: "#98FB98",
    filename: "Ice cream paradise.wav",
  },
  {
    id: 19,
    title: "Glorious Winter Ice",
    artist: "AI-SONG",
    genre: "Winter",
    plays: 1980,
    color: "#B0E0E6",
    filename: "Glorious Winter Ice.wav",
  },
  {
    id: 20,
    title: "アイスクリームくっそ食べたい",
    artist: "AI-SONG",
    genre: "Comedy",
    plays: 1920,
    color: "#FFA07A",
    filename: "アイスクリームくっそ食べたい（V5）.wav",
  },
  {
    id: 21,
    title: "Hurry! Hurry! Hurry!",
    artist: "AI-SONG",
    genre: "Dance",
    plays: 1890,
    color: "#FF6347",
    filename: "Hurry! Hurry! Hurry! .wav",
  },
  {
    id: 22,
    title: "Ice Cream and One Story",
    artist: "AI-SONG",
    genre: "Ballad",
    plays: 1860,
    color: "#DDA0DD",
    filename: "Ice Cream and One Story(V5).wav",
  },
  {
    id: 23,
    title: "アイスクリーム総選挙",
    artist: "AI-SONG",
    genre: "J-Pop",
    plays: 1820,
    color: "#D65076",
    filename: "アイスクリーム総選挙.wav",
  },
  {
    id: 24,
    title: "3秒ルール",
    artist: "AI-SONG",
    genre: "Comedy",
    plays: 1750,
    color: "#20B2AA",
    filename: "3秒ルール.wav",
  },
  {
    id: 25,
    title: "アイスだらけのcameraroll",
    artist: "AI-SONG",
    genre: "Pop",
    plays: 1700,
    color: "#9370DB",
    filename: "アイスだらけのcameraroll.wav",
  },
  {
    id: 26,
    title: "クラフトソフトクリーム",
    artist: "AI-SONG",
    genre: "Folk",
    plays: 1650,
    color: "#F5DEB3",
    filename: "クラフトソフトクリーム.wav",
  },
  {
    id: 27,
    title: "ペンギンの告白 -Ice Cream Love-",
    artist: "AI-SONG",
    genre: "Ballad",
    plays: 1600,
    color: "#4682B4",
    filename: "ペンギンの告白 -Ice Cream Love-.wav",
  },
  {
    id: 28,
    title: "アイス食べさせてクレメンス",
    artist: "AI-SONG",
    genre: "Comedy",
    plays: 1560,
    color: "#CD853F",
    filename: "アイス食べさせてクレメンス.wav",
  },
  {
    id: 29,
    title: "一日くらい大丈夫",
    artist: "AI-SONG",
    genre: "Pop",
    plays: 1520,
    color: "#5DB89A",
    filename: "一日くらい大丈夫（V5）.wav",
  },
  {
    id: 30,
    title: "アイスクリームの恨みは怖いのよ",
    artist: "AI-SONG",
    genre: "Comedy",
    plays: 1480,
    color: "#B22222",
    filename: "アイスクリームの恨みは怖いのよ (V5).wav",
  },
  {
    id: 31,
    title: "思い出のアイスキャンディー",
    artist: "AI-SONG",
    genre: "Nostalgic",
    plays: 1440,
    color: "#DAA520",
    filename: "思い出のアイスキャンディー.wav",
  },
  {
    id: 32,
    title: "レイガシノミチ",
    artist: "AI-SONG",
    genre: "J-Pop",
    plays: 1400,
    color: "#708090",
    filename: "レイガシノミチ.wav",
  },
  {
    id: 33,
    title: "僕は冬のアイスです",
    artist: "AI-SONG",
    genre: "Winter",
    plays: 1360,
    color: "#87CEEB",
    filename: "僕は冬のアイスです.wav",
  },
];

export const getRanking = (): Track[] =>
  [...tracks].sort((a, b) => b.plays - a.plays);

// 本番・開発ともに /api/audio/ 経由でストリーム
// 本番: APIルートがR2からプロキシ（CORSヘッダー付与）
// 開発: APIルートがローカルファイルを直接ストリーム
export const getAudioUrl = (filename: string): string =>
  `/api/audio/${encodeURIComponent(filename)}`;
